model_names:
  - linear
  - logistic
  - adaboost
  - forest
  - tree
  - knn
  - sdnnc
  - cdnnc

hyper:
  search_params_path: <search parameters path>
  n_candidates: 50

sourcemeter:
  path: <SM path>

  # Value can be of: ["windows", "linux", "independent"]
  os: independent

  # txt file
  err_log: <error_log_path>

flatten_log_file: <flatten_log_file_path>